color-logs: true
debug-mode: false
language-file: "lang-en.yml"

dolphin-live-time: 60
dolphin-spawn-cooldown: 120
dolphin-spawn-on-sneak-only: true
dolphin-invulnerable: false
trident-get-cooldown: 120
trident-lore: Cool Name for Trident
spawn-flying-trident: true
flying-trident-speed: 2
destroy-trident-after-use: false
trident-damage-on-use: 1
trident-can-be-picked-up: true
dolphin-has-ai: true
trident:
  enchants:
    loyalty: 5
    impaling: 10
    unbreaking: 10
